apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend 
spec:
  selector:
    matchLabels:
      app: backend 
  replicas: 2
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
      - name: backend 
        image: ${BACKEND_REPO}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
