apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend 
spec:
  selector:
    matchLabels:
      app: backend 
  replicas: 2
  template:
    metadata:
      labels:
        app: backend 
        tags.datadoghq.com/service: sre-onboarding-shinta-b7
    spec:
      containers:
      - name: backend 
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/sre-onboarding-shinta-b4:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
